### ISSUE TITLE
Zero padding doesn't work

### ISSUE THREAD

**Issue by patere** [nruotsal/node-iso11649#1]
generate('00001') returns RF7400001.
This should have been RF6800001 according to this calculator (http://www.jknc.eu/RFcalculator).

RF74 would be the correct checksum for generate('1').

> generate('1')
'RF741'
> generate('01')
'RF7401'
> generate('001')
'RF74001'
> generate('0001')
'RF740001'
> generate('00001')
'RF7400001'

**Comment by nruotsal** [comment]
Hi @patere and good catch. That calculator you are referring to is known to be a buggy one. RF7400001 in fact is a correct creditor reference for 00001.
